blog/urls.py
#!usr/bin/python3
#-*- coding:utf-8 -*-

from django.conf.urls import url
from django.urls import re_path, path

from blog.views import CategoryView, ArchiveView, DetailView, TagView, AboutView, ConnectView,SearchView

app_name='blog'
urlpatterns = [

    # 文章详情页
    re_path('post/(?P<pk>[0-9]+)/', DetailView.as_view(),name='detail'),
    # 按年月查找
    re_path('archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/', ArchiveView.as_view(), name='archives'),
    # 按分类查找
    re_path('category/(?P<pk>[0-9]+)/', CategoryView.as_view(), name='category'),
    # 按分类查找
    re_path('tag/(?P<pk>[0-9]+)/', TagView.as_view(), name='tag'),
    path('about/', AboutView.as_view(), name='about'),
    path('connect/', ConnectView.as_view(), name='connect'),
    path('search/', SearchView.as_view(), name='search'),
]

blogproject/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path, re_path
from django.views.static import serve

from blog.feeds import AllPostsRssFeed
from blog.views import IndexView
from blogproject.settings import STATIC_ROOT

urlpatterns = [
    # 首页
    path('', IndexView.as_view(), name='index'),
    # 管理界面
    path('admin/', admin.site.urls),
    # blog界面
    path('blog/', include('blog.urls', namespace='blog')),
    # 评论界面
    path('comment/', include('comments.urls', namespace='comment')),
    re_path('static/(?P<path>.*)', serve, {"document_root": STATIC_ROOT}),
    path('all/rss/', AllPostsRssFeed(), name='rss'),
]

comments/urls.py
#!/usr/bin/python3
#-*- coding: utf-8 -*-
from django.urls import re_path
from comments.views import CommentView

app_name = 'comments'
urlpatterns = [
       re_path('comment/post/(?P<post_pk>[0-9]+)/', CommentView.as_view(), name='post_comment'),
]

blog/models.py
#!usr/bin/python3
#-*- coding:utf-8 -*-

import markdown
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime

from django.utils.html import strip_tags


class Category(models.Model):
    """
        Django 要求模型必须继承 models.Model 类。
        Category 只需要一个简单的分类名 name 就可以了。
        CharField 指定了分类名 name 的数据类型，CharField 是字符型，
        CharField 的 max_length 参数指定其最大长度，超过这个长度的分类名就不能被存入数据库。
        当然 Django 还为我们提供了多种其它的数据类型，如日期时间类型 DateTimeField、整数类型 IntegerField 等等。
        Django 内置的全部类型可查看文档：
        https://docs.djangoproject.com/en/1.10/ref/models/fields/#field-types
        """
    name=models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Tag(models.Model):
    """
        标签 Tag 也比较简单，和 Category 一样。
        再次强调一定要继承 models.Model 类！
        """
    name=models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    """
        文章的数据库表稍微复杂一点，主要是涉及的字段更多。
        """
    # 文章标题
    title=models.CharField(max_length=70, verbose_name=u'文章标题')
    # 文章正文，我们使用了 TextField。
    # 存储比较短的字符串可以使用 CharField，但对于文章的正文来说可能会是一大段文本，因此使用 TextField 来存储大段文本。
    body=models.TextField(verbose_name=u'文章正文')
    # 这两个列分别表示文章的创建时间和最后一次修改时间，存储时间的字段用 DateTimeField 类型。
    created_time=models.DateTimeField(default=datetime.now, verbose_name=u'创建时间')
    modified_time=models.DateTimeField(default=datetime.now, verbose_name=u'最后修改时间')
    # 文章摘要，可以没有文章摘要，但默认情况下 CharField 要求我们必须存入数据，否则就会报错。
    # 指定 CharField 的 blank=True 参数值后就可以允许空值了。
    excerpt=models.CharField(max_length=200,blank=True, verbose_name=u'最后修改时间')
    # 这是分类与标签，分类与标签的模型我们已经定义在上面。
    # 我们在这里把文章对应的数据库表和分类、标签对应的数据库表关联了起来，但是关联形式稍微有点不同。
    # 我们规定一篇文章只能对应一个分类，但是一个分类下可以有多篇文章，所以我们使用的是 ForeignKey，即一对多的关联关系。
    # 而对于标签来说，一篇文章可以有多个标签，同一个标签下也可能有多篇文章，所以我们使用 ManyToManyField，表明这是多对多的关联关系。
    # 同时我们规定文章可以没有标签，因此为标签 tags 指定了 blank=True。
    # 如果你对 ForeignKey、ManyToManyField 不了解，请看教程中的解释，亦可参考官方文档：
    # https://docs.djangoproject.com/en/1.10/topics/db/models/#relationships
    category=models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name=u'分类')
    tags=models.ManyToManyField(Tag, blank=True)
    # 文章作者，这里 User 是从 django.contrib.auth.models 导入的。
    # django.contrib.auth 是 Django 内置的应用，专门用于处理网站用户的注册、登录等流程，User 是 Django 为我们已经写好的用户模型。
    # 这里我们通过 ForeignKey 把文章和 User 关联了起来。
    # 因为我们规定一篇文章只能有一个作者，而一个作者可能会写多篇文章，因此这是一对多的关联关系，和 Category 类似。
    author=models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=u'用户')
    click_number=models.IntegerField(default=0, verbose_name=u'点击数')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail',kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        # 如果没有填写摘要
        if not self.excerpt:
            # 首先实例化一个 Markdown 类，用于渲染 body 的文本
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            # 先将 Markdown 文本渲染成 HTML 文本
            # strip_tags 去掉 HTML 文本的全部 HTML 标签
            # 从文本摘取前 54 个字符赋给 excerpt
            self.excerpt = strip_tags(md.convert(self.body))[:54]

        # 调用父类的 save 方法将数据保存到数据库中
        super(Post, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-created_time']
        verbose_name = u'文章'
        verbose_name_plural = verbose_name

comments/models.py
from django.db import models

class Comment(models.Model):
    name=models.CharField(max_length=100, verbose_name=u'题目')
    email=models.EmailField(max_length=255, verbose_name=u'留言邮箱')
    url=models.URLField(blank=True)
    text = models.TextField(verbose_name=u'留言内容')
    created_time=models.DateTimeField(auto_now_add=True,)

    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, verbose_name=u'文章')
    def __str__(self):
        return self.text[:20]

templates/about.html
{% extends 'base.html' %}
{% load staticfiles %}

              {% block main %}
                <article class="post post-">
                    <header class="entry-header">
                        <h1 class="entry-title">关于该网站</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">声明</a></span>
                            <span class="post-author"><a href="#">huang</a></span>
                            <span class="comments-link"><a href="#">0 评论</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        本网站为黄泽昊学习所用，列为实例！
                    </div>

              {% endblock main %}
              {% block toc %}
              {% endblock toc %}

templates/base.html
{%load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>Black &amp; White</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/highlights/github.css' %}">

    <!-- js -->
    <script src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/pace.min.js' %}"></script>
    <script src="{% static 'js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'index' %}"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="{% url 'index' %}" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:about' %}" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:connect' %}" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'blog:search' %}">
                            <input type="search" name='q' placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://blog.ihave20sp.xyz">huang的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}

            </main>
            <aside class="col-md-4">
              {% block toc %}
              {% endblock toc %}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_posts as recent_post_list %}
                    <ul>
                        {% for post in recent_post_list %}
                        <li>
                            <a href="{% url 'blog:detail' post.pk %}">{{ post.title }}</a>
                        </li>
                        <li>
                        {% empty %}
                        暂无文章!
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                        <li>
                            <a href="{% url 'blog:archives' date.year date.month %}">
                               {{ date.year }}年{{ date.month }}月
                            </a>
                        </li>
                        {% empty %}
                        暂无归档！
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                        <li>
                            <a href="{% url 'blog:category' category.pk %}">{{ category.name }}<span class="post-count">{{ category.post_set.count }}</span></a>
                        </li>
                        {% empty %}
                        暂无分类！
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    {% get_alltags as tag_list %}
                    <ul>
                        {% for tag in tag_list %}
                        <li>
                            <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
                        </li>
                        {% empty %}
                        暂无标签!
                        {% endfor %}
                    </ul>
                </div>
                <div class="rss">
                    <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="http://blog.ihave20sp.xyz/" title="网页模板" target="_blank">huang的博客</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'index' %}">首页</a></li>
            <li><a href="{% url 'index' %}">博客</a></li>
            <li><a href="{% url 'blog:about' %}">关于</a></li>
            <li><a href="{% url 'blog:connect' %}">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'js/script.js' %}"></script>

</body>
</html>

templates/connect.html
{% extends 'base.html' %}
{% load staticfiles %}

              {% block main %}
                <article class="post post-">
                    <header class="entry-header">
                        <h1 class="entry-title">关于该网站</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">声明</a></span>
                            <span class="post-author"><a href="#">huang</a></span>
                            <span class="comments-link"><a href="#">0 评论</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        本网站为黄泽昊学习所用，联系qq953743087
                    </div>

              {% endblock main %}
              {% block toc %}
              {% endblock toc %}

templates/detail.html
{% extends 'base.html' %}
{% load staticfiles %}

              {% block main %}
                <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">{{ post.title }}</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
                            <span class="views-count"><a href="#">{{ post.click_number }} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        {{ post.body|safe }}
                    </div>
                </article>
                <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                    <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-4">
                                <label for="{{ form.name.id_for_label }}">名字：</label>
                                {{ form.name }}
                                {{ form.name.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.email.id_for_label }}">邮箱：</label>
                                {{ form.email }}
                                {{ form.email.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.url.id_for_label }}">网址：</label>
                                {{ form.url }}
                                {{ form.url.errors }}
                            </div>
                            <div class="col-md-12">
                                <label for="{{ form.text.id_for_label }}">评论：</label>
                                {{ form.text }}
                                {{ form.text.errors }}
                                <button type="submit" class="comment-btn">发表</button>
                            </div>
                        </div>    <!-- row -->
                    </form>
                    <div class="comment-list-panel">
                        <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
                        <ul class="comment-list list-unstyled">
                            {% for comment in comment_list %}
                            <li class="comment-item">
                                 <span class="nickname">{{ comment.name }}</span>
                                 <time class="submit-date">{{ comment.created_time }}</time>
                                 <div class="text">
                                    {{ comment.text }}
                                 </div>
                            </li>
                            {% empty %}
                            暂无评论
                            {% endfor %}

                        </ul>
                    </div>
                </section>
              {% endblock main %}
              {% block toc %}
                <div class="widget widget-content">
                    <h3 class="widget-title">文章目录</h3>
                    {{ post.toc|safe }}
                    <ul>
                        <li>
                            <a href="#">教程特点</a>
                        </li>
                        <li>
                            <a href="#">谁适合这个教程</a>
                        </li>
                        <li>
                            <a href="#">在线预览</a>
                        </li>
                        <li>
                            <a href="#">资源列表</a>
                        </li>
                        <li>
                            <a href="#">获取帮助</a>
                        </li>
                    </ul>
                </div>
                  <div class="widget-tag-cloud">
                    <ul>
                        标签：
                        {% for tag in post.tags.all %}
                            <li><a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a></li>
                        {% endfor %}
                    </ul>
                    </div>
              {% endblock toc %}

templates/index.html
{% extends 'base.html' %}
{%load staticfiles %}
              {% block main %}
                  {% if error_msg %}
                    <p>{{ error_msg }}</p>
                  {% endif %}
                {% for post in post_list %}
                   <article class="post post-{{post.pk}}">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="{% url 'blog:detail' post.pk %}">{{ post.title }}</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ post.created_time }}">{{ post.created_time}}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="#">{{ post.comment_set.count }}评论</a></span>
                            <span class="views-count"><a href="#">{{ post.click_number }} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>{{ post.excerpt }}</p>
                        <div class="read-more cl-effect-14">
                            <a href="{% url 'blog:detail' post.pk %}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                   </article>
                {% empty %}
                   <div class="no-post">暂时还没有发布的文章！</div>
                {% endfor %}
                  {% if is_paginated %}
                    <div class="pagination-simple">
                     <!-- 如果当前页还有上一页，显示一个上一页的按钮 -->
                      {% if page_obj.has_previous %}
                        <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
                      {% endif %}
                      <!-- 显示当前页面信息 -->
                      <span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</span>
                      <!-- 如果当前页还有下一页，显示一个下一页的按钮 -->
                      {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">下一页</a>
                      {% endif %}
                    </div>
                    {% endif %}
              {% endblock main %}